# Security Configuration for dp-federated-lora-lab
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: dp-federated-lora-lab-network-policy
  namespace: ml-optimization
spec:
  podSelector:
    matchLabels:
      app: dp-federated-lora-lab
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ml-optimization
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - {  }
---
apiVersion: v1
kind: Secret
metadata:
  name: dp-federated-lora-lab-secrets
  namespace: ml-optimization
type: Opaque
data:
  # Add your base64 encoded secrets here
  # Example: api_key: <base64-encoded-api-key>
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: dp-federated-lora-lab-peer-auth
  namespace: ml-optimization
spec:
  selector:
    matchLabels:
      app: dp-federated-lora-lab
  mtls:
    mode: STRICT
