version: '3.8'

services:
  dp-fed-lora-server:
    build: .
    image: dp-federated-lora:latest
    container_name: dp-fed-lora-development
    ports:
      - "8443:8443"
    environment:
      - ENVIRONMENT=development
      - SSL_ENABLED=false
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
