apiVersion: v1
kind: Namespace
metadata:
  name: dp-federated-lora
  labels:
    name: dp-federated-lora
    environment: production
    component: federated-learning
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dp-federated-lora-quota
  namespace: dp-federated-lora
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dp-federated-lora-limits
  namespace: dp-federated-lora
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container