
apiVersion: apps/v1
kind: Deployment
metadata:
  name: federated-server
  namespace: dp-federated-lora-production
  labels:
    app: federated-server
    environment: production
spec:
  replicas: 5
  strategy:
    type: Recreate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: federated-server
  template:
    metadata:
      labels:
        app: federated-server
        environment: production
    spec:
      serviceAccountName: federated-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
      - name: federated-server
        image: dp-federated-lora:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REGION
          value: "eu-central-1"
        - name: PRIVACY_EPSILON
          value: "1.0"
        - name: SSL_ENABLED
          value: "true"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: config
          mountPath: /etc/federated
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: federated-server-tls
      - name: config
        configMap:
          name: federated-server-config
---
apiVersion: v1
kind: Service
metadata:
  name: federated-server
  namespace: dp-federated-lora-production
  labels:
    app: federated-server
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: federated-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: federated-server
  namespace: dp-federated-lora-production
  labels:
    app: federated-server
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: federated-server-hpa
  namespace: dp-federated-lora-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: federated-server
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
