
apiVersion: v1
kind: Secret
metadata:
  name: federated-server-tls
  namespace: dp-federated-lora-staging
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded cert
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded key
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: federated-server-netpol
  namespace: dp-federated-lora-staging
spec:
  podSelector:
    matchLabels:
      app: federated-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: dp-federated-lora-staging
    ports:
    - protocol: TCP
      port: 8443
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: federated-server-pdb
  namespace: dp-federated-lora-staging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: federated-server
---
