name: Autonomous Security & Value Discovery

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Bandit security scan
      run: |
        bandit -r src/ -f json -o bandit-report.json || true
        bandit -r src/ -f sarif -o bandit-results.sarif || true

    - name: Upload Bandit SARIF results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: bandit-results.sarif

    - name: Run Safety check
      run: |
        safety check --json --output safety-report.json || true
        safety check --output safety-report.txt || true

    - name: Upload Safety results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: safety-report
        path: safety-report.*

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  autonomous-value-discovery:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run Value Discovery
      run: |
        python3 .terragon/simple-discovery.py
        python3 .terragon/autonomous-executor.py

    - name: Create Autonomous Enhancement PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🤖 Weekly autonomous SDLC enhancements"
        title: "[AUTO-ENHANCE] Weekly Value Discovery & Implementation"
        body: |
          ## 🤖 Autonomous SDLC Enhancement
          
          Weekly execution of the Terragon Autonomous SDLC system:
          
          - 🔍 **Value Discovery**: Analyzed repository for improvement opportunities
          - 📊 **Prioritization**: Applied WSJF+ICE+TechnicalDebt scoring
          - 🚀 **Implementation**: Executed highest-value items with validation
          - 📈 **Metrics**: Updated continuous learning database
          
          ### Changes Made
          - Updated BACKLOG.md with latest prioritized items
          - Implemented next best value enhancements
          - Updated execution metrics for learning
          
          🤖 Generated by Terragon Autonomous SDLC
        branch: weekly-autonomous-enhancement
        delete-branch: true